domains_locations:
  https://indeed.co.in:
    [bengaluru]

  https://indeed.com:
    [newyork, michigan]

job_query:
  [python developer,  web developer]

job_sort:
  date

job_age:
  "3"

job_loop_pages:
  2

job_type:
  fulltime, remote

keywords:
  [css, CSS, html, HTML, HTML5, CSS3, illustrator, Illustrator, photoshop, Photoshop]

output:
  data/indeed_jobs.csv

semaphore:
  5
